### ISSUE TITLE
NameError: name 'pn2_ext' is not defined

### ISSUE THREAD

**Issue by cravisjan97** [tiangeluo/Learning-to-Group#1]
Hi!

Thanks for sharing the code and pre-trained models! I am trying to run the test code on PartNet dataset and I get the above error. I see a message stating that I have to compile the source files before using pointnet2 cuda extension. How do I do this? 

Note: I am using a conda environment with cuda 9.0 and pytorch 1.0

Thanks in advance!

**Comment by tiangeluo** [comment]
Hi,

Have you already compiled the extension by running ```bash compile.sh```?

**Comment by cravisjan97** [comment]
Yes, I did. I had a couple of warnings but no error

**Comment by tiangeluo** [comment]
Thanks. 

After running ```bash compile.sh```, can you find ```pn2_ext.cpython-36m-x86_64-linux-gnu.so``` in ```shaper/models/pointnet2```? 

Also, have you tried the provided  [docker image](https://hub.docker.com/r/tiangeluo/learning-to-group)?

**Comment by cravisjan97** [comment]
I see ```pn2_ext.cpython-37m-x86_64-linux-gnu.so``` in ```shaper/models/pointnet2/```. When I run ```from shaper.models.pointnet2 import pn2_ext```, I get the following error: ```pn2_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE```. I do not have Tensorflow installed in my virtual environment. Should I install TensorFlow? If yes, what version of Tensorflow should I install?

I tried to run ```docker pull tiangeluo/learning-to-group:v0``` and I get the following error: 
```Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=tiangeluo%2Flearning-to-group&tag=v0: dial unix /var/run/docker.sock: connect: permission denied```

**Comment by cravisjan97** [comment]
Hi! When I run ```bash compile.sh```, I see the compilation done with ```D_GLIBCXX_USE_CX11_ABI=0```. But I know that I will have to set ```D_GLIBCXX_USE_CX11_ABI=1``` for my system. This might solve the undefined symbol error. How do I make this change in ```setup.py```?

**Comment by tiangeluo** [comment]
Hi, really sorry for the late response due to PhD applications. Could you please try the newest [docker image](https://hub.docker.com/r/tiangeluo/learning-to-group)? I test it on my own servers, and it works fine.

**Comment by yuchenlichuck** [comment]
> I see `pn2_ext.cpython-37m-x86_64-linux-gnu.so` in `shaper/models/pointnet2/`. When I run `from shaper.models.pointnet2 import pn2_ext`, I get the following error: `pn2_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE`. I do not have Tensorflow installed in my virtual environment. Should I install TensorFlow? If yes, what version of Tensorflow should I install?
> 
> I tried to run `docker pull tiangeluo/learning-to-group:v0` and I get the following error:
> `Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=tiangeluo%2Flearning-to-group&tag=v0: dial unix /var/run/docker.sock: connect: permission denied`

Hi, it may because you don't have sudo access to the server. I also got the same bug on the server that with administration access

**Comment by tiangeluo** [comment]
Thank you for your help answer, Yuchen. I close this issue for now due to no further questions.
